# Generated by Django 5.1.1 on 2024-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available'), ('for rent', 'for rent')], max_length=50),
        ),
    ]
